travis:
  secure:
    BINSTAR_TOKEN: XRfd86S8VXJj8xLqApH3x+igYGfSSlH/9nr5t/kT344DWL33el4Bm3GHtFeJa2WdPqrWFZfJ6DMw+VyhBlzyAxNcaT/HWCpNFJYGEI7NXl1fI7CCzdKjLHR9fLIt/oCaCv09Uqikzuc88g8eD9Lx4mUuriK6LWnDu3ZX5LW1nJd2s/17KjaQaIbHMcM1eHSCMoz3vvOaK72JXw9lcR4sLKIasRLMuJQDObwzOpi4wfNxbRynhRdJ5VaNw51tzBIFzCNSGAMMlux4k2TQdLe9m80zz+RfB74ZzhZAGEqmGfxaBl2ZF0PJZvoqJwiwUtIplV7SBQpvv5EF19wAhf+/f5HcWEVoZct321O4uh3kX4fTGtFKuxVeEmLZBtm1jeI2MjpNdbgeA8Bic1LeYvro8CwZ8ut3Np8gWQozwjuxEoQx5Om+GX9sWnf2a1x9ZQtP4hyaiO4TadOYrnHcay2M8zTQeNUbRVRR+zrQmdGi7evjU4/1n5wY00b7o6jQQ4xwGyms+vcyp7lXbgANUkM7pbIpFWf4yn6gll0AiBFoYdL8ZW7jJTPJ8apXhTJr+4nuMu20bkE53erLwcBjKZP/DRe6oTrrezpPJdLgyt+FqSNlrIXqyQEpButkuilCRuMF3daz5SKS5QzliZa8gGJHGY4nEHJ+QuHqFQffeA31dVM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
